# Generated by Django 5.2.6 on 2025-12-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_order_siparis_tipi_mesaikayit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
