import re

# label, fallback UserAccess field
FEATURE_GROUPS = [
    ("Siparişler", [
        ("orders.view_list", "Sipariş Listesi", "can_view_orders"),
        ("orders.view_detail", "Sipariş Detayı", "can_view_orders"),
        ("orders.create", "Sipariş Oluştur", "can_create_orders"),
        ("orders.multi_create", "Toplu Sipariş Oluştur", "can_create_orders"),
        ("orders.edit", "Sipariş Düzenle", "can_edit_orders"),
        ("orders.delete", "Sipariş Sil", "can_delete_orders"),
        ("orders.update_production", "Üretim Aşaması Güncelle", "can_update_production"),
        ("orders.transfer_history", "Üretim Geçmişi Aktar", "can_edit_orders"),
        ("orders.upload_image", "Sipariş Görseli Ekle", "can_edit_orders"),
        ("orders.delete_image", "Sipariş Görseli Sil", "can_edit_orders"),
        ("orders.view_image", "Sipariş Görselini Gör", "can_view_orders"),
        ("orders.print", "Sipariş Yazdır", "can_create_orders"),
        ("orders.label_print", "Etiket Yazdır", "can_create_orders"),
        ("orders.mark_printed", "Çıktı Alındı İşaretle", "can_create_orders"),
        ("orders.export_excel", "Sipariş Excel İndir", "can_create_orders"),
        ("orders.toggle_active", "Sipariş Aktif / Pasif", "can_edit_orders"),
        ("orders.price_history", "Geçmiş Fiyat Sorgula", "can_view_reports"),
    ]),
    ("Müşteri / Katalog", [
        ("catalog.customers", "Müşteri Listesi / Kartı", "can_view_reports"),
        ("catalog.customer_edit", "Müşteri Düzenle", "can_view_reports"),
        ("catalog.customer_create", "Müşteri Ekle / Aktif Et", "can_create_orders"),
        ("catalog.customer_disable", "Müşteri Pasife Al", "can_create_orders"),
        ("catalog.color_manage", "Renk Ekle / Pasife Al", "can_create_orders"),
        ("catalog.size_manage", "Beden Ekle / Pasife Al", "can_create_orders"),
        ("catalog.product_code_manage", "Ürün Kodu Ekle / Düzenle / Pasife Al", "can_create_orders"),
    ]),
    ("Planlama / Operasyon", [
        ("planning.main", "Planlama", "can_manage_planning"),
        ("planning.shipment", "Sevkiyat Planlama", "can_manage_planning"),
        ("planning.actions", "Planlama İşlemleri", "can_manage_planning"),
        ("operations.fason_reports", "Fason Raporları", "can_view_reports"),
        ("operations.fason_create", "Fasoncu Ekle", "can_view_reports"),
        ("operations.embroidery_reports", "Nakışçı Raporları", "can_view_reports"),
        ("operations.embroidery_create", "Nakışçı Ekle", "can_view_reports"),
        ("operations.reminders", "Hatırlatmalar", "can_view_reports"),
    ]),
    ("Stok / Depo", [
        ("stock.depots", "Depolar", "can_view_depots"),
        ("stock.ready_transfer", "Hazırdan Ver", "can_view_depots"),
        ("stock.add_from_order", "Siparişten Stoğa Ekle", "can_view_depots"),
        ("stock.inventory", "Stok / Ambar Kartları", "can_view_depots"),
        ("stock.movements", "Stok Hareketi Ekle", "can_view_depots"),
    ]),
    ("Ürün / Maliyet / Finans", [
        ("products.cards", "Ürün Kartları", "can_view_costs"),
        ("products.materials", "Malzemeler", "can_view_costs"),
        ("products.exchange_rate", "Kur Güncelle", "can_view_costs"),
        ("products.price_list", "Fiyat Listesi", "can_view_costs"),
        ("products.price_list_manage", "Fiyat Listesi Ayarları / Aktif-Pasif", "can_view_costs"),
        ("products.price_list_excel", "Fiyat Listesi Excel", "can_view_costs"),
        ("products.finance", "Sipariş Finans Hareketleri", "can_view_shipping_finance"),
        ("products.cost_legacy", "Eski Ürün Maliyet Listesi", "can_view_costs"),
    ]),
    ("Sipariş Föyü / Showroom", [
        ("showroom.main", "Sipariş Föyü", "can_view_costs"),
        ("showroom.drafts", "Taslak Föyler", "can_view_costs"),
        ("showroom.approved", "Onaylanan Föyler", "can_view_costs"),
        ("showroom.customer_history", "Müşteri Föy Geçmişi", "can_view_costs"),
        ("showroom.edit", "Föy Düzenle / Kaydet", "can_view_costs"),
        ("showroom.approve", "Föy Onayla / Durum Değiştir", "can_view_costs"),
        ("showroom.print", "Föy Yazdır", "can_view_costs"),
        ("showroom.transfer", "Föyden Sipariş Oluştur", "can_view_costs"),
        ("showroom.staff_qr_transfer", "QR Sepetini Föye Aktar", "can_view_costs"),
    ]),
    ("Raporlar", [
        ("reports.main", "Genel Raporlar", "can_view_reports"),
        ("reports.dashboard", "Rapor Dashboard", "can_view_reports"),
        ("reports.shipped", "Giden / Sevk Edilen Ürünler", "can_view_reports"),
        ("reports.customer", "Müşteri Raporları", "can_view_reports"),
        ("reports.staff", "Staff Reports / Personel Hareketleri", "can_view_reports"),
        ("reports.personnel", "Personel Raporu", "can_view_personnel"),
        ("reports.shipping_finance", "Sevkiyat Finans", "can_view_shipping_finance"),
    ]),
    ("Puantaj / Mesai", [
        ("attendance.scan", "Giriş / Çıkış QR Okutma", None),
        ("attendance.punch", "Giriş / Çıkış Kaydetme", None),
        ("attendance.dashboard", "Puantaj Paneli", "can_view_attendance"),
        ("attendance.reports", "Puantaj Raporları", "can_view_attendance"),
        ("attendance.devices", "Cihaz Onayları", "can_view_attendance"),
        ("attendance.qr_manage", "Puantaj QR Gör / Yazdır", "can_view_attendance"),
        ("attendance.edit", "Puantaj Kaydı / İş Yeri Konumu Düzenle", "can_view_attendance"),
    ]),
    ("Kalite", [
        ("quality.orders", "Sipariş Hata / Şikayet Kayıtları", "can_manage_quality"),
        ("quality.actions", "Hata Çöz / Yeniden Aç", "can_manage_quality"),
        ("quality.report", "Kalite Raporu", "can_manage_quality"),
        ("quality.personnel", "Personel Kalite Detayı", "can_view_personnel"),
    ]),
    ("Ekip / Yönetim", [
        ("team.users", "Ekipler / Kullanıcı Yönetimi", "can_manage_users"),
        ("team.employee_detail", "Personel Detay Sayfası", "can_manage_users"),
        ("team.audit", "Kullanıcı İşlem Kayıtları", "can_manage_users"),
        ("settings.main", "Ayarlar", "can_view_settings"),
        ("assistant.main", "AI Asistan", "can_view_assistant"),
        ("notifications.main", "Bildirimler", "can_view_orders"),
    ]),
]

FEATURES = {
    key: {"label": label, "fallback": fallback, "group": group}
    for group, items in FEATURE_GROUPS
    for key, label, fallback in items
}

_RULES = [
    (re.compile(r"^/$"), "orders.view_list"),
    (re.compile(r"^/order/new/$"), "orders.create"),
    (re.compile(r"^/orders/multi-create/$"), "orders.multi_create"),
    (re.compile(r"^/order/\d+/edit/$"), "orders.edit"),
    (re.compile(r"^/order/\d+/delete/$"), "orders.delete"),
    (re.compile(r"^/orders/\d+/update/$"), "orders.update_production"),
    (re.compile(r"^/order/\d+/production-transfer(?:/search)?/$"), "orders.transfer_history"),
    (re.compile(r"^/orders/\d+/(?:upload-image|add-image)/$"), "orders.upload_image"),
    (re.compile(r"^/order/\d+/delete-image-by-url/$"), "orders.delete_image"),
    (re.compile(r"^/images/\d+/delete/$"), "orders.delete_image"),
    (re.compile(r"^/images/\d+/$"), "orders.view_image"),
    (re.compile(r"^/orders/print/$"), "orders.print"),
    (re.compile(r"^/orders/label/print/$"), "orders.label_print"),
    (re.compile(r"^/order/\d+/cikti-alindi/$"), "orders.mark_printed"),
    (re.compile(r"^/orders/export/excel/$"), "orders.export_excel"),
    (re.compile(r"^/order/\d+/toggle-active/$"), "orders.toggle_active"),
    (re.compile(r"^/ajax/gecmis-fiyatlar/$"), "orders.price_history"),
    (re.compile(r"^/order-no/"), "orders.view_detail"),
    (re.compile(r"^/order/\d+/$"), "orders.view_detail"),

    (re.compile(r"^/musteriler/$"), "catalog.customers"),
    (re.compile(r"^/musteriler/\d+/duzenle/$"), "catalog.customer_edit"),
    (re.compile(r"^/musteri/new/$|^/ajax/musteri/ekle/$"), "catalog.customer_create"),
    (re.compile(r"^/ajax/musteri/pasif-yap/$"), "catalog.customer_disable"),
    (re.compile(r"^/ajax/renk/"), "catalog.color_manage"),
    (re.compile(r"^/ajax/beden/"), "catalog.size_manage"),
    (re.compile(r"^/ajax/urun-kod/"), "catalog.product_code_manage"),

    (re.compile(r"^/planlama/sevkiyat/$"), "planning.shipment"),
    (re.compile(r"^/planlama/(?:sevkiyat/.+|not/.+|kaydet/)$"), "planning.actions"),
    (re.compile(r"^/planlama/$"), "planning.main"),
    (re.compile(r"^/reports/fasoncu/"), "operations.fason_reports"),
    (re.compile(r"^/fasoncu/yeni/$"), "operations.fason_create"),
    (re.compile(r"^/reports/nakisci/"), "operations.embroidery_reports"),
    (re.compile(r"^/nakisci/yeni/$"), "operations.embroidery_create"),
    (re.compile(r"^/hatirlatmalar/"), "operations.reminders"),

    (re.compile(r"^/depolar/hazirdan-ver/"), "stock.ready_transfer"),
    (re.compile(r"^/order/\d+/stok-ekle/$"), "stock.add_from_order"),
    (re.compile(r"^/depolar/"), "stock.depots"),
    (re.compile(r"^/stok/[^/]+/(?:malzeme|urun)/"), "stock.inventory"),
    (re.compile(r"^/stok/[^/]+/(?:malzeme-hareket|urun-hareket)/"), "stock.movements"),
    (re.compile(r"^/stok/"), "stock.inventory"),

    (re.compile(r"^/urun-kartlari/kur-guncelle/$"), "products.exchange_rate"),
    (re.compile(r"^/urun-kartlari/fiyat-listesi/(?:kaydet|durum)/$"), "products.price_list_manage"),
    (re.compile(r"^/urun-kartlari/fiyat-listesi/excel/$"), "products.price_list_excel"),
    (re.compile(r"^/urun-kartlari/fiyat-listesi/$"), "products.price_list"),
    (re.compile(r"^/urun-kartlari/finans/"), "products.finance"),
    (re.compile(r"^/urun-kartlari/malzemeler/$"), "products.materials"),
    (re.compile(r"^/urun-kartlari/(?:depo-stoklari/|durum-degistir/|\d+/)?$"), "products.cards"),
    (re.compile(r"^/product-costs/$"), "products.cost_legacy"),

    (re.compile(r"^/urun-kartlari/showroom-foyu/taslaklar/$"), "showroom.drafts"),
    (re.compile(r"^/urun-kartlari/showroom-foyu/onaylananlar/$"), "showroom.approved"),
    (re.compile(r"^/urun-kartlari/showroom-foyu/musteri/"), "showroom.customer_history"),
    (re.compile(r"^/urun-kartlari/showroom-foyu/kayit/\d+/duzenle(?:/kaydet)?/$"), "showroom.edit"),
    (re.compile(r"^/urun-kartlari/showroom-foyu/kayit/\d+/durum-degistir/$"), "showroom.approve"),
    (re.compile(r"^/urun-kartlari/showroom-foyu/kayit/\d+/yazdir/$"), "showroom.print"),
    (re.compile(r"^/urun-kartlari/showroom-foyu/kayit/\d+/siparis-(?:onizleme|olustur)/$"), "showroom.transfer"),
    (re.compile(r"^/urun-kartlari/showroom-foyu/"), "showroom.main"),
    (re.compile(r"^/urun-kartlari/qr/sepet-aktar/|^/urun-kartlari/qr/sepet-kodu/$"), "showroom.staff_qr_transfer"),

    (re.compile(r"^/staff-reports/$"), "reports.staff"),
    (re.compile(r"^/reports/sevkiyat-finans/$"), "reports.shipping_finance"),
    (re.compile(r"^/reports/personel/$"), "reports.personnel"),
    (re.compile(r"^/reports/musteri-karsilastirma/"), "reports.customer"),
    (re.compile(r"^/reports/giden-urunler/$|^/reports/shipped-live/$"), "reports.shipped"),
    (re.compile(r"^/reports/dashboard/$|^/reports/home/$"), "reports.dashboard"),
    (re.compile(r"^/reports/$"), "reports.main"),

    (re.compile(r"^/attendance/$"), "attendance.scan"),
    (re.compile(r"^/attendance/punch/$"), "attendance.punch"),
    (re.compile(r"^/attendance/(?:qr\.png|qr-yazdir/)$"), "attendance.qr_manage"),
    (re.compile(r"^/attendance/cihazlar/"), "attendance.devices"),
    (re.compile(r"^/attendance/panel/(?:kayit-duzenle|konum-kaydet)/$"), "attendance.edit"),
    (re.compile(r"^/attendance/panel/$"), "attendance.dashboard"),
    (re.compile(r"^/attendance/rapor/"), "attendance.reports"),

    (re.compile(r"^/kalite/order/"), "quality.orders"),
    (re.compile(r"^/kalite/issue/"), "quality.actions"),
    (re.compile(r"^/kalite/report/$"), "quality.report"),
    (re.compile(r"^/kalite/personel/"), "quality.personnel"),

    (re.compile(r"^/users/\d+/islem-kayitlari/$"), "team.audit"),
    (re.compile(r"^/users/\d+/$"), "team.employee_detail"),
    (re.compile(r"^/users/$"), "team.users"),
    (re.compile(r"^/ayarlar/"), "settings.main"),
    (re.compile(r"^/(?:asistan/|api/assistant/)"), "assistant.main"),
    (re.compile(r"^/(?:notifications/|bildirim/)"), "notifications.main"),
]


def feature_for_path(path):
    for pattern, key in _RULES:
        if pattern.search(path):
            return key
    return None
