from django.db import migrations, models
import django.db.models.deletion


CREATE_TABLE_IF_MISSING = """
CREATE TABLE IF NOT EXISTS product_cards_showroomorderlink (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL,
    draft_id bigint NOT NULL
        REFERENCES product_cards_showroomdraft(id)
        DEFERRABLE INITIALLY DEFERRED,
    draft_item_id bigint NULL
        REFERENCES product_cards_showroomdraftitem(id)
        DEFERRABLE INITIALLY DEFERRED,
    order_id bigint NOT NULL UNIQUE
        REFERENCES core_order(id)
        DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE product_cards_showroomorderlink
    ADD COLUMN IF NOT EXISTS draft_item_id bigint NULL;
CREATE INDEX IF NOT EXISTS product_cards_showroomorderlink_draft_id_idx
    ON product_cards_showroomorderlink (draft_id);
CREATE INDEX IF NOT EXISTS product_cards_showroomorderlink_draft_item_id_idx
    ON product_cards_showroomorderlink (draft_item_id);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("product_cards", "0027_showroomdraft_pricing_operations"),
        ("core", "0063_consignmentmovement_source_event"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_TABLE_IF_MISSING, migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ShowroomOrderLink",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("draft", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="order_links", to="product_cards.showroomdraft")),
                        ("draft_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_links", to="product_cards.showroomdraftitem")),
                        ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="showroom_link", to="core.order")),
                    ],
                    options={"ordering": ["id"]},
                ),
            ],
        ),
    ]
