from django.urls import path
from . import views, status_views, finance_views, price_list_views, showroom_views, showroom_print_views, showroom_transfer_views, public_product_views

urlpatterns = [
    path("", views.product_card_list, name="product_card_list"),
    path("kur-guncelle/", views.refresh_exchange_rate, name="refresh_exchange_rate"),
    path("fiyat-listesi/", price_list_views.price_list, name="price_list"),
    path("showroom-foyu/", showroom_views.showroom_page, name="showroom_page"),
    path("showroom-foyu/taslaklar/", showroom_views.showroom_drafts_page, name="showroom_drafts_page"),
    path("showroom-foyu/onaylananlar/", showroom_views.showroom_approved_page, name="showroom_approved_page"),
    path("showroom-foyu/kayit/<int:draft_id>/", showroom_views.showroom_detail_page, name="showroom_detail_page"),
    path("showroom-foyu/kayit/<int:draft_id>/yazdir/", showroom_print_views.showroom_print_page, name="showroom_print_page"),
    path("showroom-foyu/kayit/<int:draft_id>/duzenle/", showroom_views.showroom_edit_page, name="showroom_edit_page"),
    path("showroom-foyu/kayit/<int:draft_id>/duzenle/kaydet/", showroom_views.showroom_edit_save, name="showroom_edit_save"),
    path("showroom-foyu/kayit/<int:draft_id>/siparis-onizleme/", showroom_transfer_views.showroom_transfer_preview, name="showroom_transfer_preview"),
    path("showroom-foyu/kayit/<int:draft_id>/siparis-olustur/", showroom_transfer_views.showroom_transfer_create, name="showroom_transfer_create"),
    path("showroom-foyu/taslak/", showroom_views.showroom_draft_load, name="showroom_draft_load"),
    path("showroom-foyu/taslak/otomatik-kaydet/", showroom_views.showroom_draft_autosave, name="showroom_draft_autosave"),
    path("showroom-foyu/taslak/indirim-kaydet/", showroom_views.showroom_draft_discount_save, name="showroom_draft_discount_save"),
    path("showroom-foyu/kayitlar/", showroom_views.showroom_archive_list, name="showroom_archive_list"),
    path("showroom-foyu/islem/", showroom_views.showroom_draft_action, name="showroom_draft_action"),
    path("qr/urun/<str:code>/", public_product_views.public_product_page, name="public_product_page"),
    path("fiyat-listesi/kaydet/", price_list_views.save_price_list_settings, name="save_price_list_settings"),
    path("fiyat-listesi/excel/", price_list_views.export_price_list_excel, name="export_price_list_excel"),
    path("fiyat-listesi/durum/", price_list_views.toggle_price_list_status, name="toggle_price_list_status"),
    path("durum-degistir/", status_views.toggle_product_card_status, name="toggle_product_card_status"),
    path("finans/<int:order_id>/", finance_views.order_finance_movements, name="order_finance_movements"),
    path("finans/<int:order_id>/hareket-ekle/", finance_views.add_order_finance_movement, name="add_order_finance_movement"),
    path("malzemeler/", views.material_list, name="material_list"),
    path("depo-stoklari/", views.warehouse_inventory, name="warehouse_inventory"),
    path("<int:card_id>/", views.product_card_detail, name="product_card_detail"),
]
